In [2]:
import numpy as np

In [10]:
a = np.array([1,2,3],dtype= complex)
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)

[1.+0.j 2.+0.j 3.+0.j]
1
complex128
(3,)


In [8]:
a = np.array([
    [1,2,3],
    [2.,3.,4.]
])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)

[[1. 2. 3.]
 [2. 3. 4.]]
2
float64
(2, 3)


In [9]:
a = np.array([
    [[1,2,3],
    [8,9,6]],

    [[5,6,3],
    [44,55,66]]
])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)

[[[ 1  2  3]
  [ 8  9  6]]

 [[ 5  6  3]
  [44 55 66]]]
3
int32
(2, 2, 3)


In [12]:
null = np.zeros((3,5))
print(null)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
ones = np.ones((2,4))
ones=10 * ones
#print(ones)
arr = np.arange(1,13).reshape(4,3)

arr = arr**2
arr
arr2= np.arange(6,18).reshape(3,4)
arr3 = arr @ arr2 # marix multiplication
arr3

array([[ 172,  186,  200,  214],
       [ 850,  927, 1004, 1081],
       [2068, 2262, 2456, 2650],
       [3826, 4191, 4556, 4921]])

In [25]:
a = np.linspace(1,np.pi,6,dtype= float)
a

array([1.        , 1.42831853, 1.85663706, 2.28495559, 2.71327412,
       3.14159265])

In [36]:
b = np.array([0,4,1,3,2,6,]).reshape(2,3)
b.sum()
b.min()
b.max()
b

array([[0, 4, 1],
       [3, 2, 6]])

In [41]:
b
print(b.sum(axis=0)) # sum of each column
print(b.sum(axis=1)) # sum of each row
print(b.cumsum(axis=1)) #cumulative sum of each col.


[3 6 7]
[ 5 11]
[[ 0  4  5]
 [ 3  5 11]]
