In [2]:
import numpy as np

In [10]:
a = np.array([1,2,3],dtype= complex)
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)

[1.+0.j 2.+0.j 3.+0.j]
1
complex128
(3,)


In [8]:
a = np.array([
    [1,2,3],
    [2.,3.,4.]
])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)

[[1. 2. 3.]
 [2. 3. 4.]]
2
float64
(2, 3)


In [9]:
a = np.array([
    [[1,2,3],
    [8,9,6]],

    [[5,6,3],
    [44,55,66]]
])
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)

[[[ 1  2  3]
  [ 8  9  6]]

 [[ 5  6  3]
  [44 55 66]]]
3
int32
(2, 2, 3)


In [12]:
null = np.zeros((3,5))
print(null)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
ones = np.ones((2,4))
ones=10 * ones
#print(ones)
arr = np.arange(1,13).reshape(4,3)

arr = arr**2
arr
arr2= np.arange(6,18).reshape(3,4)
arr3 = arr @ arr2 # marix multiplication
arr3

array([[ 172,  186,  200,  214],
       [ 850,  927, 1004, 1081],
       [2068, 2262, 2456, 2650],
       [3826, 4191, 4556, 4921]])

In [25]:
a = np.linspace(1,np.pi,6,dtype= float)
a

array([1.        , 1.42831853, 1.85663706, 2.28495559, 2.71327412,
       3.14159265])

In [3]:
b = np.array([0,4,1,3,2,6,]).reshape(2,3)
b.sum()
# b.min()
# b.max()
# b

16

In [41]:
b
print(b.sum(axis=0)) # sum of each column
print(b.sum(axis=1)) # sum of each row
print(b.cumsum(axis=1)) #cumulative sum of each col.


[3 6 7]
[ 5 11]
[[ 0  4  5]
 [ 3  5 11]]


In [2]:
arr= np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
for i in arr :
    print(i**(1/2))

[0.         1.         1.41421356 1.73205081 2.        ]
[2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
[3.16227766 3.31662479 3.46410162 3.60555128 3.74165739]
[3.87298335 4.         4.12310563 4.24264069 4.35889894]


In [6]:
for i in arr.flat :
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [9]:
arr.T # transpose

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

## reshape , ravel() do not modify original array rather creates a new array, but resize  modifies the original array
### ravel() is used to flatten the array

In [21]:
arr= np.arange(10,22)
arr.resize(2,5)
arr.shape

(2, 5)

In [26]:
l=list(range(1,11,2))
d = np.array(l)
d

array([1, 3, 5, 7, 9])

## Slicing in multidimentional array

In [33]:
a=np.arange(20).reshape(5,4)
print(a)
a[0:6,2] #[0:6] will access the rows and 2 will print 3rd element of each row


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([ 2,  6, 10, 14, 18])

In [34]:
a[-1,1:4]

array([17, 18, 19])

In [40]:
a=np.arange(60).reshape(4,3,5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]]

 [[45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [41]:
a[1,0:2,2]

array([17, 22])

## verticle and horizontal stack of arrays

In [50]:
a =np.arange(1,7).reshape(2,3)
b =np.arange(10,16).reshape(2,3)
c = np.vstack((a,b))
d = np.hstack((a,b))
print(c)
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]
 [13 14 15]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]]


## Split the arrays

In [55]:
e = np.arange(0,24).reshape(2,12)
res = np.hsplit(e,4)
for i in res :
    print(i)

[[ 0  1  2]
 [12 13 14]]
[[ 3  4  5]
 [15 16 17]]
[[ 6  7  8]
 [18 19 20]]
[[ 9 10 11]
 [21 22 23]]


In [56]:
e = np.arange(0,24).reshape(12,2)
res = np.vsplit(e,4)
for i in res :
    print(i)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]
[[12 13]
 [14 15]
 [16 17]]
[[18 19]
 [20 21]
 [22 23]]


## read the documentation of "nditer"